<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "t_article_category".
 *
 * @property integer $article_category_id
 * @property string $category_name
 * @property integer $created_at
 */
class ActiveRecord extends \yii\db\ActiveRecord
{
    /**
     * restful才会调用
     * @return array
     */
    public function fields()
    {
        $fields = parent::fields(); // TODO: Change the autogenerated stub
        $fields['created_at'] = function($model) {
            return !empty($model->created_at) ? date('Y-m-d H:i', $model->created_at) : '';
        };

        $fields['updated_at'] = function($model) {
            return !empty($model->updated_at) ? date('Y-m-d H:i', $model->updated_at) : '';
        };

        $fields['deleted_at'] = function($model) {
            return !empty($model->deleted_at) ? date('Y-m-d H:i', $model->deleted_at) : '';
        };
        return $fields;
    }

}
